### ISSUE TITLE
Logo Design: WorkerAppClient

### ISSUE THREAD

**Issue by baranpirincal** [bugtamer/WorkerAppClient#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by bugtamer** [comment]
HI Baran!
Unfortunately, its part of our evaluation of a training course which is actually finished, so the project has no longer support, as WorkerApp2 and some other repos with the same purpose.
In any case, we appreciate a lot your collaboration and your interest to help us.
May be we could collaborate in future projects.

Best Regards,

Bugtamer
Programmer
